name: E2E-TESTS

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  e2e-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run start
      - run: npm run test-e2e:chrome:headless
